In [3]:
import tensorflow as tf

print(tf.__version__)

2.20.0-rc0


In [ ]:

# Create tensors with tf.constant()

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
# Creating vector
vector= tf.constant([12,30])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 30], dtype=int32)>

In [8]:
vector.ndim

1

In [10]:
matrix= tf.constant([[10,7],[8,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [13]:
another_matrix = tf.constant([[10.,7.],[11.,9.],[12.,9.],[13.,10.],[43.,41.]], dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(5, 2), dtype=float16, numpy=
array([[10.,  7.],
       [11.,  9.],
       [12.,  9.],
       [13., 10.],
       [43., 41.]], dtype=float16)>