In [ ]:
!pip install ipykernel


In [ ]:
import tensorflow as tf

print(tf.__version__)

In [ ]:

# Create tensors with tf.constant()

scalar=tf.constant(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
# Creating vector
vector= tf.constant([12,30])
vector

In [ ]:
vector.ndim

In [ ]:
matrix= tf.constant([[10,7],[8,10]])

matrix

In [ ]:
matrix.ndim

In [ ]:
another_matrix = tf.constant([[10.,7.],[11.,9.],[12.,9.],[13.,10.],[43.,41.]], dtype=tf.float16)

another_matrix

Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
some_list=[1,2,3,4]
some_list[2:]

In [ ]:
rank_4_tensor= tf.zeros(shape=[2,3,4,5])
rank_4_tensor
rank_4_tensor.shape

In [ ]:
rank_4_tensor[:1,:1,:1,:]

In [ ]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim


In [ ]:
rank_2_tensor

In [ ]:
rank_3_tensor=rank_2_tensor[..., tf.newaxis]
rank_3_tensor

rank_3_tensor.shape

Matrix multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

The inner dimensions must match
The resulting matrix has the shape of the outer dimensions

In [ ]:
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor


In [ ]:
tensor+10

In [ ]:
tensor

In [ ]:
tf.multiply(tensor,10)

In [ ]:
tf.matmul(tensor, tensor)

In [ ]:
tensor, tensor

In [ ]:
tensor @ tensor


In [ ]:
X= tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])


Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])



X,Y

# Find the positional maximum and minimum


In [46]:
# Create a new tensor for finding positional minimum and maxmimum

tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [48]:
id= tf.argmax(F)

print(id.numpy())
print(F[id].numpy())


42
0.9671384


In [49]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [52]:
x = tf.constant([[[1], [2], [3]]])  
print(x.shape)

y= tf.squeeze(x)

print(y)
print(y.shape)


(1, 3, 1)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)
